apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  strategy:
    type: Recreate
  template:
    metadata:
      name: pod_grafana
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana_img
        imagePullPolicy: Never
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  annotations:
    metallb.universe.tf/allow-shared-ip: ajeanett
  labels:
    app: grafana
spec:
  selector:
    app: grafana
  ports:
  - port: 3000
    name: grafana
    targetPort: 3000
    protocol: TCP
  type: LoadBalancer
  loadBalancerIP: 192.168.99.164