apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  strategy:
    type: Recreate
  template:
    metadata:
      name: pod_wordpress
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress_img
        imagePullPolicy: Never
        ports:
        - containerPort: 5050

---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  annotations:
    metallb.universe.tf/allow-shared-ip: ajeanett
  labels:
    app: wordpress
spec:
  selector:
    app: wordpress
  ports:
  - port: 5050
    name: wordpress
    targetPort: 5050
    protocol: TCP
  type: LoadBalancer
  loadBalancerIP: 192.168.99.164